[mqtt]
client-id = "iot-svr-00"
host = "lhlj-prod"
port = 40185
#username = "jktest"
#password = "jktest"
topic = ["iot-gatex"]

[influxdb]
url = "http://192.168.1.70:8086"
bucket = "iot"
token = "admin-token=="
