# IEC-104 从站
[[drivers]]
type             = "iec104"
name             = "substation-a"   # 唯一实例名，出现在 topic 和日志中
host             = "192.168.10.11"
port             = 2404
ca               = 1
auto_interrogate = true
qoi              = 20               # 20 = 全站总召唤

[mqtt]
host = "127.0.0.1"
port = 1883
client_id = "iot-gatex"
username = "iot-gatex"
password = "iot-gatex"
topic_prefix = "iot-gatex"
qos = 1             # 0 / 1 / 2