# IEC-104 从站
[[drivers]]
type             = "iec104"
name             = "substation-a"   # 唯一实例名，出现在 topic 和日志中
host             = "localhost"
port             = 2404
get-gi           = false
get-gi-interval  = "1m"
get-kwh          = true
get-kwh-interval = "30s"

[mqtt]
host = "lhlj-prod"
port = 40185
client-id = "iot-gatex"
#username = "iot-gatex"
#password = "iot-gatex"
topic = "iot-gatex"
#qos = 1             # 0 / 1 / 2
#flush-interval = "15s"
